/**
 * @file    uat_fec.c
 * @brief   Clean-room Reed-Solomon FEC over GF(256) for the UAT physical layer.
 *
 * @details
 *   Implements the standard RS decoding pipeline — syndrome computation,
 *   Berlekamp-Massey error-locator search, Chien root search, and Forney error
 *   evaluation — plus a systematic encoder used by the host tests. The field and
 *   code parameters are the PUBLIC UAT values from RTCA DO-282B:
 *
 *     GF(256), primitive polynomial 0x187  (x^8 + x^7 + x^2 + x + 1)
 *     first consecutive root fcr = 120, primitive-element step prim = 1
 *     RS(30,18) basic ADS-B, RS(48,34) long ADS-B, RS(92,72) uplink block
 *
 *   The math is written from first principles (any coding-theory text describes
 *   this exact algorithm); NO libfec / dump978 / GPL code was consulted. Only the
 *   numeric parameters above — which are spec facts, not code — are used.
 *
 *   The decoder is ALLOCATION-FREE and table-driven so it runs deterministically
 *   on Core 0. It is invoked only AFTER a sync hit (a few times per second), so
 *   its cost is amortized to near-zero on the hot path.
 *
 * @copyright Novabox / ADSBin. Receive-only, experimental, non-certified.
 *
 * Clean-room from the standard RS algorithm + the public DO-282B UAT FEC
 * parameters. No code adapted from libfec / dump978 / any GPL source.
 */

#include "uat_fec.h"

#include <string.h>

/* ═══════════════════════════════════════════════════════════════════════════
 *  GF(256) field definition.
 *
 *  The field is generated by the primitive polynomial 0x187. We precompute two
 *  256-entry tables: gf_exp[i] = alpha^i (the antilog), and gf_log[x] = the i
 *  such that alpha^i == x (the log). With these, multiply is an add of logs and
 *  inverse is a negate of the log — turning all field arithmetic into table
 *  lookups, which is what keeps the decoder fast and branch-light.
 * ═══════════════════════════════════════════════════════════════════════════ */

/* UAT field generator polynomial (DO-282B): x^8 + x^7 + x^2 + x + 1 = 0x187.
 * Only the low 8 bits matter at runtime (bit 8 is the implicit reduction term). */
#define GF_POLY   0x187u

/* First consecutive root of the generator polynomial and the primitive step.
 * The RS generator is product over j in [fcr, fcr+nroots) of (x - alpha^(prim*j)). */
#define GF_FCR    120
#define GF_PRIM   1

/* gf_exp is sized 512 so that exponents up to 2*254 can be read without a modulo
 * in the inner loops: gf_exp[i] for i in [0,255) holds alpha^i, and we mirror the
 * cycle into [255,510) so a "log-add then index" never needs a conditional. */
static uint8_t gf_exp[512];
static uint8_t gf_log[256];
static bool    gf_ready = false;

/**
 * @brief Build the GF(256) exp/log tables from the primitive polynomial 0x187.
 *
 * @details
 *   Start at alpha^0 = 1 and repeatedly multiply by the primitive element alpha
 *   (a left shift by one bit), reducing modulo GF_POLY whenever bit 8 sets. After
 *   255 steps the sequence returns to 1 (alpha has order 255 in GF(256)). We
 *   record each power in gf_exp and its inverse mapping in gf_log, then duplicate
 *   the exp cycle into the upper half of the 512-entry table so log-sums up to
 *   508 index it directly.
 */
void uat_fec_init(void)
{
    if (gf_ready) {
        return;
    }

    /* Walk the multiplicative cycle: x starts at 1 (= alpha^0). */
    uint32_t x = 1;
    for (int i = 0; i < 255; i++) {
        gf_exp[i] = (uint8_t)x;
        gf_log[x] = (uint8_t)i;

        /* Multiply by alpha: shift left one, fold in GF_POLY if it overflowed
         * past 8 bits (the polynomial-reduction step). */
        x <<= 1;
        if (x & 0x100u) {
            x ^= GF_POLY;
        }
    }

    /* gf_log[0] is undefined (0 has no log); leave it 0 — callers never log 0. */
    gf_log[0] = 0;

    /* Mirror the 255-long cycle into [255, 510) so a log-sum index never wraps. */
    for (int i = 255; i < 512; i++) {
        gf_exp[i] = gf_exp[i - 255];
    }

    gf_ready = true;
}

/* ── Field arithmetic (all O(1) table lookups) ──────────────────────────────── */

/** @brief GF(256) multiply: a * b. Zero is handled explicitly (no log of 0). */
static inline uint8_t gf_mul(uint8_t a, uint8_t b)
{
    if (a == 0 || b == 0) {
        return 0;
    }
    /* log(a*b) = log(a) + log(b); the 512-entry exp table absorbs the carry. */
    return gf_exp[gf_log[a] + gf_log[b]];
}

/** @brief GF(256) multiplicative inverse: 1 / a (a must be non-zero). */
static inline uint8_t gf_inv(uint8_t a)
{
    /* alpha^(255 - log a) is the inverse, since alpha^255 == 1. */
    return gf_exp[255 - gf_log[a]];
}

/** @brief Raise the primitive element alpha to a power: alpha^p (p any int). */
static inline uint8_t gf_alpha_pow(int p)
{
    /* Reduce the exponent into [0,255) then look it up. */
    int e = p % 255;
    if (e < 0) {
        e += 255;
    }
    return gf_exp[e];
}

/* ═══════════════════════════════════════════════════════════════════════════
 *  Generator polynomial.
 *
 *  g(x) = product_{j=0}^{nroots-1} (x - alpha^(prim*(fcr + j))). We build it once
 *  per (nroots) on demand; nroots is small (12/14/20) so an on-stack build is
 *  cheap and keeps the encoder allocation-free.
 * ═══════════════════════════════════════════════════════════════════════════ */

/* Largest parity length across all three UAT codes is 20 (uplink). */
#define MAX_NROOTS  20

/**
 * @brief Build the systematic RS generator polynomial for @p nroots parities.
 *
 * @param gen     Receives nroots+1 coefficients, gen[0] = highest degree (== 1).
 * @param nroots  Number of parity symbols (= n - k).
 */
static void build_generator(uint8_t gen[MAX_NROOTS + 1], int nroots)
{
    /* Start with g(x) = 1. */
    memset(gen, 0, (size_t)(nroots + 1));
    gen[0] = 1;
    int glen = 1;   /* current number of coefficients in gen */

    /* Multiply in (x - alpha^(prim*(fcr+j))) for each root. */
    for (int j = 0; j < nroots; j++) {
        uint8_t root = gf_alpha_pow(GF_PRIM * (GF_FCR + j));

        /* Polynomial multiply gen *= (x - root). Walk high-to-low so we can do it
         * in place: new[i] = old[i-1] + old[i]*root. */
        gen[glen] = 0;                 /* extend by one degree */
        for (int i = glen; i > 0; i--) {
            gen[i] = (uint8_t)(gen[i - 1] ^ gf_mul(gen[i], root));
        }
        gen[0] = gf_mul(gen[0], root); /* the constant term picks up the root */
        glen++;
    }
}

/* ═══════════════════════════════════════════════════════════════════════════
 *  Systematic encoder (host-test / TX only).
 * ═══════════════════════════════════════════════════════════════════════════ */

void uat_fec_rs_encode(uint8_t *data, int n, int k)
{
    uat_fec_init();

    int nroots = n - k;
    uint8_t gen[MAX_NROOTS + 1];
    build_generator(gen, nroots);

    /* Parity lives in data[k..n); clear it, then run the LFSR division of the
     * k message bytes by g(x). The remainder is the parity. */
    memset(&data[k], 0, (size_t)nroots);

    for (int i = 0; i < k; i++) {
        /* Feedback = current message byte XOR the top parity byte. */
        uint8_t fb = (uint8_t)(data[i] ^ data[k]);

        /* Shift the parity register left by one and mix in fb * gen coefficients.
         * gen[nroots] is the leading 1 and is implicit, so we use gen[nroots-1-j]. */
        if (fb != 0) {
            for (int j = 0; j < nroots - 1; j++) {
                data[k + j] = (uint8_t)(data[k + j + 1] ^ gf_mul(fb, gen[nroots - 1 - j]));
            }
            data[n - 1] = (uint8_t)gf_mul(fb, gen[0]);
        } else {
            for (int j = 0; j < nroots - 1; j++) {
                data[k + j] = data[k + j + 1];
            }
            data[n - 1] = 0;
        }
    }
}

/* ═══════════════════════════════════════════════════════════════════════════
 *  Decoder: syndromes -> Berlekamp-Massey -> Chien -> Forney.
 * ═══════════════════════════════════════════════════════════════════════════ */

/* Working sizes bounded by the largest code (n=92, nroots=20). */
#define MAX_N        92

int uat_fec_rs_decode(uint8_t *data, int n, int k)
{
    uat_fec_init();

    int nroots = n - k;

    /* ── 1) Syndromes. S_j = R(alpha^(prim*(fcr+j))) for j in [0,nroots). If all
     *       syndromes are zero the codeword is already valid (no errors). ─────── */
    uint8_t synd[MAX_NROOTS];
    bool all_zero = true;
    for (int j = 0; j < nroots; j++) {
        uint8_t root = gf_alpha_pow(GF_PRIM * (GF_FCR + j));
        /* Horner evaluation of the received polynomial at this root. */
        uint8_t s = 0;
        for (int i = 0; i < n; i++) {
            s = (uint8_t)(gf_mul(s, root) ^ data[i]);
        }
        synd[j] = s;
        if (s != 0) {
            all_zero = false;
        }
    }
    if (all_zero) {
        return 0;   /* clean codeword. */
    }

    /* ── 2) Berlekamp-Massey: find the error-locator polynomial Lambda(x). ────── */
    uint8_t lambda[MAX_NROOTS + 1];   /* error locator, lambda[0] = 1 */
    uint8_t prev[MAX_NROOTS + 1];     /* previous lambda (C(x) copy)  */
    uint8_t tmp[MAX_NROOTS + 1];
    memset(lambda, 0, sizeof(lambda));
    memset(prev,   0, sizeof(prev));
    lambda[0] = 1;
    prev[0]   = 1;
    int L = 0;            /* current number of assumed errors */
    int m = 1;            /* steps since the last length change */
    uint8_t b = 1;        /* last non-zero discrepancy */

    for (int r = 0; r < nroots; r++) {
        /* Discrepancy delta = S_r + sum_{i=1..L} lambda[i] * S_{r-i}. */
        uint8_t delta = synd[r];
        for (int i = 1; i <= L; i++) {
            delta ^= gf_mul(lambda[i], synd[r - i]);
        }

        if (delta == 0) {
            /* No discrepancy — just advance the shift counter. */
            m++;
        } else if (2 * L <= r) {
            /* Length change: T(x) = lambda(x) - (delta/b) x^m * prev(x). */
            memcpy(tmp, lambda, sizeof(lambda));
            uint8_t coef = gf_mul(delta, gf_inv(b));
            for (int i = 0; i + m <= nroots; i++) {
                lambda[i + m] ^= gf_mul(coef, prev[i]);
            }
            L = r + 1 - L;
            memcpy(prev, tmp, sizeof(tmp));
            b = delta;
            m = 1;
        } else {
            /* No length change: lambda(x) -= (delta/b) x^m * prev(x). */
            uint8_t coef = gf_mul(delta, gf_inv(b));
            for (int i = 0; i + m <= nroots; i++) {
                lambda[i + m] ^= gf_mul(coef, prev[i]);
            }
            m++;
        }
    }

    /* The number of errors equals deg(lambda) = L. If L exceeds the correction
     * capability the codeword is uncorrectable. */
    if (L <= 0 || L > nroots / 2) {
        return -1;
    }

    /* ── 3) Chien search: find the byte indices in error.
     *
     *  POSITION CONVENTION (critical). The syndrome Horner loop above feeds
     *  data[0] first, so data[0] is the coefficient of x^(n-1) and data[n-1] is
     *  the coefficient of x^0. The error locator for the byte at index `idx` is
     *  therefore X_l = alpha^(prim * p) where p = n-1-idx is that byte's POWER.
     *  A Chien root is where lambda(X_l^-1) == 0. We walk idx directly and derive
     *  p from it so the byte index we record matches the buffer layout. (Getting
     *  this map wrong corrects the right magnitude at the WRONG byte.) ─────────── */
    int err_pos[MAX_NROOTS];
    int nerr = 0;
    for (int idx = 0; idx < n; idx++) {
        int p = n - 1 - idx;                       /* this byte's polynomial power */
        /* X_l^-1 = alpha^(-prim*p); evaluate lambda there. */
        uint8_t x_inv = gf_alpha_pow(-GF_PRIM * p);
        uint8_t eval = 0;
        uint8_t xp = 1;
        for (int i = 0; i <= L; i++) {
            eval ^= gf_mul(lambda[i], xp);
            xp = gf_mul(xp, x_inv);
        }
        if (eval == 0) {
            if (nerr < MAX_NROOTS) {
                err_pos[nerr] = idx;               /* record the BUFFER index. */
            }
            nerr++;
        }
    }

    /* The locator must have exactly L distinct roots inside the codeword; if not,
     * the error pattern is not correctable (e.g. > t errors mimicking a valid L). */
    if (nerr != L) {
        return -1;
    }

    /* ── 4) Forney: compute each error magnitude.
     *       Build the error-evaluator Omega(x) = [S(x) * lambda(x)] mod x^nroots,
     *       then e_l = - Omega(X_l^-1) / lambda'(X_l^-1) with the fcr offset. ──── */

    /* Syndrome polynomial S(x) = sum S_j x^j. Omega = (S * lambda) truncated. */
    uint8_t omega[MAX_NROOTS];
    memset(omega, 0, sizeof(omega));
    for (int i = 0; i < nroots; i++) {
        uint8_t acc = 0;
        for (int j = 0; j <= i; j++) {
            acc ^= gf_mul(synd[i - j], lambda[j]);
        }
        omega[i] = acc;
    }

    int corrected = 0;
    for (int e = 0; e < nerr; e++) {
        int pos = err_pos[e];
        int p   = n - 1 - pos;          /* polynomial power for this buffer index. */

        /* X_l = alpha^(prim*p) is the error locator; its inverse is the Chien
         * root we found. Evaluate Omega and lambda' at that inverse. */
        uint8_t xl     = gf_alpha_pow(GF_PRIM * p);
        uint8_t xl_inv = gf_inv(xl);

        /* Omega(xl_inv). */
        uint8_t omega_val = 0;
        uint8_t xp = 1;
        for (int i = 0; i < nroots; i++) {
            omega_val ^= gf_mul(omega[i], xp);
            xp = gf_mul(xp, xl_inv);
        }

        /* Formal derivative lambda'(xl_inv): in GF(2^m) only the odd-degree terms
         * survive differentiation, and the x is divided out — evaluate sum of the
         * odd-index lambda coefficients times (xl_inv)^(i-1). */
        uint8_t deriv = 0;
        uint8_t xq = 1;                 /* (xl_inv)^(i-1) for i = 1,3,5,... */
        for (int i = 1; i <= L; i += 2) {
            deriv ^= gf_mul(lambda[i], xq);
            /* Advance xq by two powers of xl_inv to reach the next odd index. */
            xq = gf_mul(xq, gf_mul(xl_inv, xl_inv));
        }
        if (deriv == 0) {
            return -1;                  /* singular — not correctable. */
        }

        /* Magnitude = X_l^(1-fcr) * Omega(X_l^-1) / lambda'(X_l^-1).
         * The X_l^(1-fcr) factor accounts for the generator's fcr offset; the
         * power p (not the buffer index) is what defines X_l. */
        uint8_t scale = gf_alpha_pow(GF_PRIM * p * (1 - GF_FCR));
        uint8_t mag   = gf_mul(scale, gf_mul(omega_val, gf_inv(deriv)));

        /* Apply the correction. */
        data[pos] ^= mag;
        corrected++;
    }

    return corrected;
}

/* ── Convenience wrappers for the two ADS-B code sizes. ──────────────────────── */

int uat_fec_adsb_short_decode(uint8_t *cw30)
{
    return uat_fec_rs_decode(cw30, UAT_RS_ADSB_SHORT_N, UAT_RS_ADSB_SHORT_K);
}

int uat_fec_adsb_long_decode(uint8_t *cw48)
{
    return uat_fec_rs_decode(cw48, UAT_RS_ADSB_LONG_N, UAT_RS_ADSB_LONG_K);
}

/* ═══════════════════════════════════════════════════════════════════════════
 *  Uplink frame: deinterleave 6 blocks, RS-decode each, concatenate data parts.
 *
 *  On the air the 6 codewords are byte-interleaved: on-air byte at index
 *  (i*BLOCKS + block) belongs to codeword `block` at position `i`. We transpose
 *  back into 6 contiguous 92-byte codewords, decode each, and concatenate the
 *  corrected 72-byte data regions into the 432-byte payload.
 * ═══════════════════════════════════════════════════════════════════════════ */

bool uat_fec_uplink_decode(const uint8_t *frame_in, uint8_t *data_out,
                           int *total_corrected, int *block_errors)
{
    uat_fec_init();

    int total = 0;
    int failed = 0;

    /* Process one interleave block at a time so only a single 92-byte codeword
     * scratch is needed (allocation-free, deterministic). */
    for (int block = 0; block < UAT_RS_UPLINK_BLOCKS; block++) {
        uint8_t cw[UAT_RS_UPLINK_N];

        /* Deinterleave this block's 92 bytes out of the 552-byte frame. */
        for (int i = 0; i < UAT_RS_UPLINK_N; i++) {
            cw[i] = frame_in[i * UAT_RS_UPLINK_BLOCKS + block];
        }

        /* RS-decode it. */
        int c = uat_fec_rs_decode(cw, UAT_RS_UPLINK_N, UAT_RS_UPLINK_K);
        if (c < 0) {
            failed++;
            /* Copy the (uncorrected) data part anyway as best effort. */
            memcpy(&data_out[block * UAT_RS_UPLINK_K], cw, UAT_RS_UPLINK_K);
        } else {
            total += c;
            memcpy(&data_out[block * UAT_RS_UPLINK_K], cw, UAT_RS_UPLINK_K);
        }
    }

    if (total_corrected) {
        *total_corrected = total;
    }
    if (block_errors) {
        *block_errors = failed;
    }
    return failed == 0;
}
